language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install -r requirements.txt
script:
- "./run-tests"
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: okXcGkF1/80+cHSCzVTITH2f/IlQWdxRzjn2yBlDkZq0IAioJXVMPdLE7oI8HDxmDNlrLOj9ZPR3jmqyncXxM6+ONaIY8WoubJZ67negTi6lPL1of0/iW1u01KIcar0hHaY+KeJRN+8S3N6f3A+8X+S/5m/cEIaMMvw3Zb8RX8VPhHU1CWcnlq1cu8ZhCpQWy+qAx/giLWoUBToCF3XE0NdmO1zUU867IjDeQBt5oFDKWvH1MP2t87zpJ1PROQupo3Dq8w82FO4R467THTUzmnBlegJjY5jqLqnYq75CxNMUJZ3rNfYp41wi+8rcGk2K0h/S33zkV5kfGUWVZGEyZ8lasoRX9pZ39edxYwMOtSqrVRJcY8gJuLr0DoPS6qb6I2Gds8OKsPrUnLQ9Iv5UOvVyU/GwWUnhuoN4vLLUJGb4JHcP3Vuw5ZpieZ1c8i9bZp/rnyj6lx7HPDzVN5wjaEybDI1itDVOEbQ12Mch4KWiLxdbS+joqFWVGeRVdCH9kEJ3l2qb2X+7TAUEzZCC5qDJv4J995JqWRKKeMpXz3jRyq/BcijQgAXdixRu/NMQnMCETN5o+WflnoKYkJCTTkcER0DvSeQ8FDvb+/+pzjHaVqw8Ko6ckwxkw4/cHoVS8v91ZbjyK/GbhK1/E99bWPnebeb9hHCDLZ0n3/qQFFY=
