[project]
name = "pyraxial"
version = "0.1.0a"
description = ""
authors = [
    {name = "Mick Krippendorf", email = "m.krippendorf@freenet.de"},
]
dependencies = [
    "intervaltree~=3.1",
]
requires-python = ">=3.9"
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
