[project]
name = 'pyraxial'
version = '0.1.11b'
description = 'An algebra for paraxial (i.e. axis-aligned) rectangles.'
authors = [
    {name = 'Mick Krippendorf', email = 'm.krippendorf@freenet.de'},
]
dependencies = [
    "sortedcontainers~=2.4"]
requires-python = '>=3.6'
dynamic = ['classifiers']
license = {text = 'MIT'}
readme = 'README.md'
keywords = ['bounding-box']
classifiers = [
  'Development Status :: 4 - Beta',
  'Intended Audience :: Developers',
  'Operating System :: OS Independent',
  'Topic :: Software Development :: Libraries :: Python Modules',
]

[project.urls]
homepage = 'https://pillmuncher.github.io/pyraxial'
documentation = 'https://pillmuncher.github.io/pyraxial'
repository = 'https://github.com/pillmuncher/pyraxial'

[build-system]
requires = ['pdm-pep517']
build-backend = 'pdm.pep517.api'

[tool]
[tool.pdm]
[tool.pdm.dev-dependencies]
editor = []
test = []
dev = []
