#!/bin/sh
echo 'testing:'
coverage3 erase
PYTHONPATH=".":PYTHONPATH

for i in *.py tests/*.py; do
    echo
    echo $i
    coverage3 run -a $i
done
echo
echo 'coverage:'
echo
coverage3 report -m --include="./*.py"
coverage3 html --include="./*.py" -d test.out
